version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ape-postgres
    environment:
      POSTGRES_DB: ape_db
      POSTGRES_USER: ape_user
      POSTGRES_PASSWORD: ape_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ape_user -d ape_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
